version: "3.9"

services:
  back:
    build: ./back_end
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
  front:
    build: ./front_end
    command: npm run serve
    ports:
      - "8080:8080"
    depends_on:
      - "back"
