version: "3.9"

services:
  db:
    image: "postgres:11"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_NAME=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=notes"
  back:
    image: "back_end"
    build: "./back_end"
    command: "python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - "db"
  front:
    image: "front_end"
    build: "./front_end"
    command: "npm run serve"
    ports:
      - "8080:8080"
    depends_on:
      - "back"
